### ISSUE TITLE
Build crashes with node 12

### ISSUE THREAD

**Issue by gdepouilly** [atom/nsfw#10]
### Description

When building `v1.0.25` with `node-gyp v4.0.0` and `node.js v12.6.0`, it crashes (see logs attached)

### Steps to Reproduce

`npm install @atom/nsfw`

**Reproduces how often:**

Always

### Additional Information

https://github.com/Axosoft/nsfw/ published a release which add`node 12` support, and fix my issue (see https://github.com/Axosoft/nsfw/pull/76/commits)

As I'm not proficient in C++, could someone report it here please ? 

<details><summary>logs</summary>

```

> @atom/nsfw@1.0.25 install /home/projects/xxx/yyy/node_modules/@atom/nsfw
> node-gyp rebuild

make: Entering directory '/home/projects/xxx/yyy/node_modules/@atom/nsfw/build'
  CXX(target) Release/obj.target/nsfw/src/NSFW.o
In file included from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
../../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/NSFW.cpp: In static member function ‘static void NSFW::fireErrorCallback(uv_async_t*)’:
../src/NSFW.cpp:51:44: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   51 |   baton->nsfw->mErrorCallback->Call(1, argv);
      |                                            ^
In file included from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
../../../nan/nan.h:1740:3: note: declared here
 1740 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/NSFW.cpp: In static member function ‘static void NSFW::fireEventCallback(uv_async_t*)’:
../src/NSFW.cpp:75:104: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   75 |     jsEvent->Set(New<v8::String>("action").ToLocalChecked(), New<v8::Number>((*baton->events)[i]->type));
      |                                                                                                        ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/v8-internal.h:14,
                 from /home/.cache/node-gyp/12.6.0/include/node/v8.h:25,
                 from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:3359:26: note: declared here
 3359 |                     bool Set(Local<Value> key, Local<Value> value));
      |                          ^~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/NSFW.cpp:76:133: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   76 |     jsEvent->Set(New<v8::String>("directory").ToLocalChecked(), New<v8::String>((*baton->events)[i]->fromDirectory).ToLocalChecked());
      |                                                                                                                                     ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/v8-internal.h:14,
                 from /home/.cache/node-gyp/12.6.0/include/node/v8.h:25,
                 from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:3359:26: note: declared here
 3359 |                     bool Set(Local<Value> key, Local<Value> value));
      |                          ^~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/NSFW.cpp:79:128: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   79 |       jsEvent->Set(New<v8::String>("oldFile").ToLocalChecked(), New<v8::String>((*baton->events)[i]->fromFile).ToLocalChecked());
      |                                                                                                                                ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/v8-internal.h:14,
                 from /home/.cache/node-gyp/12.6.0/include/node/v8.h:25,
                 from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:3359:26: note: declared here
 3359 |                     bool Set(Local<Value> key, Local<Value> value));
      |                          ^~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/NSFW.cpp:80:136: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   80 |       jsEvent->Set(New<v8::String>("newDirectory").ToLocalChecked(), New<v8::String>((*baton->events)[i]->toDirectory).ToLocalChecked());
      |                                                                                                                                        ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/v8-internal.h:14,
                 from /home/.cache/node-gyp/12.6.0/include/node/v8.h:25,
                 from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:3359:26: note: declared here
 3359 |                     bool Set(Local<Value> key, Local<Value> value));
      |                          ^~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/NSFW.cpp:81:126: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   81 |       jsEvent->Set(New<v8::String>("newFile").ToLocalChecked(), New<v8::String>((*baton->events)[i]->toFile).ToLocalChecked());
      |                                                                                                                              ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/v8-internal.h:14,
                 from /home/.cache/node-gyp/12.6.0/include/node/v8.h:25,
                 from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:3359:26: note: declared here
 3359 |                     bool Set(Local<Value> key, Local<Value> value));
      |                          ^~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/NSFW.cpp:83:125: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   83 |       jsEvent->Set(New<v8::String>("file").ToLocalChecked(), New<v8::String>((*baton->events)[i]->fromFile).ToLocalChecked());
      |                                                                                                                             ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/v8-internal.h:14,
                 from /home/.cache/node-gyp/12.6.0/include/node/v8.h:25,
                 from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:3359:26: note: declared here
 3359 |                     bool Set(Local<Value> key, Local<Value> value));
      |                          ^~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/NSFW.cpp:86:31: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   86 |     eventArray->Set(i, jsEvent);
      |                               ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/v8-internal.h:14,
                 from /home/.cache/node-gyp/12.6.0/include/node/v8.h:25,
                 from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:3368:26: note: declared here
 3368 |                     bool Set(uint32_t index, Local<Value> value));
      |                          ^~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/NSFW.cpp:93:44: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   93 |   baton->nsfw->mEventCallback->Call(1, argv);
      |                                            ^
In file included from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
../../../nan/nan.h:1740:3: note: declared here
 1740 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/NSFW.cpp: In static member function ‘static void NSFW::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/NSFW.cpp:149:38: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
  149 |   constructor.Reset(tpl->GetFunction());
      |                                      ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:5948:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 5948 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/.cache/node-gyp/12.6.0/include/node/v8.h:5948:46: note:   candidate expects 1 argument, 0 provided
../src/NSFW.cpp:150:74: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
  150 |   Set(target, New<v8::String>("NSFW").ToLocalChecked(), tpl->GetFunction());
      |                                                                          ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:5948:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 5948 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/.cache/node-gyp/12.6.0/include/node/v8.h:5948:46: note:   candidate expects 1 argument, 0 provided
../src/NSFW.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NSFW::JSNew(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/NSFW.cpp:177:46: error: no matching function for call to ‘v8::Value::Uint32Value()’
  177 |   uint32_t debounceMS = info[0]->Uint32Value();
      |                                              ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:2567:41: note: candidate: ‘v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const’
 2567 |   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
      |                                         ^~~~~~~~~~~
/home/.cache/node-gyp/12.6.0/include/node/v8.h:2567:41: note:   candidate expects 1 argument, 0 provided
../src/NSFW.cpp:178:53: error: no matching function for call to ‘v8::Value::ToString()’
  178 |   v8::String::Utf8Value utf8Value(info[1]->ToString());
      |                                                     ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:2528:44: note: candidate: ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
 2528 |   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
      |                                            ^~~~~~~~
/home/.cache/node-gyp/12.6.0/include/node/v8.h:2528:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/.cache/node-gyp/12.6.0/include/node/v8-internal.h:14,
                 from /home/.cache/node-gyp/12.6.0/include/node/v8.h:25,
                 from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:2544:31: note: candidate: ‘v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const’
 2544 |                 Local<String> ToString(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/.cache/node-gyp/12.6.0/include/node/v8.h:2544:31: note:   candidate expects 1 argument, 0 provided
 2544 |                 Local<String> ToString(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/NSFW.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NSFW::Start(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/NSFW.cpp:209:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  209 |     callback->Call(1, argv);
      |                           ^
In file included from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
../../../nan/nan.h:1740:3: note: declared here
 1740 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/NSFW.cpp:214:78: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  214 |   New(nsfw->mPersistentHandle)->Set(New("nsfw").ToLocalChecked(), info.This());
      |                                                                              ^
In file included from /home/.cache/node-gyp/12.6.0/include/node/v8-internal.h:14,
                 from /home/.cache/node-gyp/12.6.0/include/node/v8.h:25,
                 from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h:3359:26: note: declared here
 3359 |                     bool Set(Local<Value> key, Local<Value> value));
      |                          ^~~
/home/.cache/node-gyp/12.6.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
  326 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/NSFW.cpp: In member function ‘virtual void NSFW::StartWorker::HandleOKCallback()’:
../src/NSFW.cpp:255:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  255 |     callback->Call(1, argv);
      |                           ^
In file included from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
../../../nan/nan.h:1740:3: note: declared here
 1740 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/NSFW.cpp:257:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  257 |     callback->Call(0, NULL);
      |                           ^
In file included from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
../../../nan/nan.h:1740:3: note: declared here
 1740 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/NSFW.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NSFW::Stop(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/NSFW.cpp:282:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  282 |     callback->Call(1, argv);
      |                           ^
In file included from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
../../../nan/nan.h:1740:3: note: declared here
 1740 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
../src/NSFW.cpp: In member function ‘virtual void NSFW::StopWorker::HandleOKCallback()’:
../src/NSFW.cpp:324:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
  324 |   callback->Call(0, NULL);
      |                         ^
In file included from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
../../../nan/nan.h:1740:3: note: declared here
 1740 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
In file included from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
../src/NSFW.cpp: At global scope:
/home/.cache/node-gyp/12.6.0/include/node/node.h:556:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  556 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/.cache/node-gyp/12.6.0/include/node/node.h:590:3: note: in expansion of macro ‘NODE_MODULE_X’
  590 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/NSFW.cpp:327:1: note: in expansion of macro ‘NODE_MODULE’
  327 | NODE_MODULE(nsfw, NSFW::Init)
      | ^~~~~~~~~~~
In file included from /home/.cache/node-gyp/12.6.0/include/node/node.h:63,
                 from ../../../nan/nan.h:54,
                 from ../src/../includes/NSFW.h:5,
                 from ../src/NSFW.cpp:1:
/home/.cache/node-gyp/12.6.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/.cache/node-gyp/12.6.0/include/node/node_object_wrap.h:84:78:   required from here
/home/.cache/node-gyp/12.6.0/include/node/v8.h:9846:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9846 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/.cache/node-gyp/12.6.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../nan/nan_object_wrap.h:65:61:   required from here
/home/.cache/node-gyp/12.6.0/include/node/v8.h:9846:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [nsfw.target.mk:124: Release/obj.target/nsfw/src/NSFW.o] Error 1
make: Leaving directory '/home/projects/xxx/yyy/node_modules/@atom/nsfw/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.1.17-300.fc30.x86_64
gyp ERR! command "/home/.nvm/versions/node/v12.6.0/bin/node" "/home/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/projects/xxx/yyy/node_modules/@atom/nsfw
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @atom/nsfw@1.0.25 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @atom/nsfw@1.0.25 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2019-07-19T08_35_11_868Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @xxx/yyy@3.0.0 bootstrap: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @xxx/yyy@3.0.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2019-07-19T08_35_12_163Z-debug.log
```

**Comment by rsese** [comment]
Thanks for the report!

> As I'm not proficient in C++, could someone report it here please ?

I think this issue is ok as is though for future issues, please don't remove any sections and fill things out as much as possible (for example, the `Prerequisites` section was removed).

**Comment by yvele** [comment]
Are this the only thing we need to report? https://github.com/Axosoft/nsfw/commit/462dfb8d51ca54dae4bf9e986ebadfa6abb8a8b8

Along with CI matrix https://github.com/Axosoft/nsfw/commit/9cf41b8d999b785358ea43b32cb586c07e4cfdf0

Also, as a more global question, what exactly brings this Atom fork to the original https://github.com/Axosoft/nsfw ?

**Comment by rsese** [comment]
Thanks for opening a pull request @yvele -

> Are this the only thing we need to report? 

By "report" do you mean which commits need to be pulled in?  If so, then whoever reviews your pull request will determine if more needs to be done.

> Also, as a more global question, what exactly brings this Atom fork to the original https://github.com/Axosoft/nsfw ?

I think it's done manually when necessary, see https://github.com/atom/nsfw/pull/8 for example.
