### ISSUE TITLE
Why this fork?

### ISSUE THREAD

**Issue by yvele** [atom/nsfw#12]
Why has this been forked from the native https://github.com/Axosoft/nsfw and published on another npm package named `@atom/nsfw` https://www.npmjs.com/package/@atom/nsfw ?

**Comment by aminya** [comment]
Very good question. Let me know if you have an answer! 

It seems it started because of a simple bug fix and later it fell behind its upstream! Now, upstream has written the package using Napi which is much better than the current Atom version.

Quote from [this pull request](https://github.com/Axosoft/nsfw/pull/41#issuecomment-351173093) (probably because of using the fs from the X-ray project)
> we plan to transition away from this library this year so it's hard to justify spending more time on it. I'm sorry. I'll go ahead and close.

Later upstream merged the same pull request: https://github.com/Axosoft/nsfw/pull/47

I looked over the rest of the commits. They are very minor changes that they could merge into upstream.  

I don't think there is much justification anymore for using this fork! Especially because this is blocking me from updating Atom's Electron to 7. It does not build anymore in newer versions of Electron or Node.

```js
 D:\a\1\s\node_modules\@atom\nsfw>if not defined npm_config_node_gyp (node "D:\a\1\s\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\a\1\s\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
 Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
   NSFW.cpp
   Queue.cpp
   NativeInterface.cpp
   Controller.cpp
   Watcher.cpp
   win_delay_load_hook.cc
 c:\users\vssadministrator\appdata\local\node-gyp\cache\7.3.2\include\node\v8.h(8515): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\NSFW.cpp) [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
   c:\users\vssadministrator\appdata\local\node-gyp\cache\7.3.2\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\NSFW.cpp)
 c:\users\vssadministrator\appdata\local\node-gyp\cache\7.3.2\include\node\v8.h(8524): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\NSFW.cpp) [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
   c:\users\vssadministrator\appdata\local\node-gyp\cache\7.3.2\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\NSFW.cpp)
 ..\src\NSFW.cpp(51): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
   D:\a\1\s\node_modules\@atom\nsfw\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
 ..\src\NSFW.cpp(75): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
 ..\src\NSFW.cpp(76): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
 ..\src\NSFW.cpp(79): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
 ..\src\NSFW.cpp(80): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
 ..\src\NSFW.cpp(81): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
 ..\src\NSFW.cpp(83): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
 ..\src\NSFW.cpp(86): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
 ..\src\NSFW.cpp(93): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
   D:\a\1\s\node_modules\@atom\nsfw\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
 ..\src\NSFW.cpp(216): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
 ..\src\NSFW.cpp(211): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
   D:\a\1\s\node_modules\@atom\nsfw\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
 ..\src\NSFW.cpp(257): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
   D:\a\1\s\node_modules\@atom\nsfw\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
 ..\src\NSFW.cpp(259): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
   D:\a\1\s\node_modules\@atom\nsfw\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
 ..\src\NSFW.cpp(284): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
   D:\a\1\s\node_modules\@atom\nsfw\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
 ..\src\NSFW.cpp(326): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\a\1\s\node_modules\@atom\nsfw\build\nsfw.vcxproj]
   D:\a\1\s\node_modules\@atom\nsfw\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
 
 gyp ERR! build error 
 gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
 gyp ERR! stack     at ChildProcess.onExit (D:\a\1\s\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
 gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
 gyp ERR! System Windows_NT 10.0.14393
 gyp ERR! command "D:\\a\\1\\s\\apm\\node_modules\\atom-package-manager\\bin\\node.exe" "D:\\a\\1\\s\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
 gyp ERR! cwd D:\a\1\s\node_modules\@atom\nsfw
 gyp ERR! node -v v10.20.1
 gyp ERR! node-gyp -v v5.1.0
 gyp ERR! not ok 
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! @atom/nsfw@1.0.26 install: `node-gyp rebuild`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the @atom/nsfw@1.0.26 install script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
 npm ERR! A complete log of this run can be found in:
 npm ERR!     C:\npm\cache\_logs\2020-08-02T05_20_41_308Z-debug.log[39m
 child_process.js:637
     throw err;
     ^
 
 Error: Command failed: D:\a\1\s\apm\node_modules\atom-package-manager\bin\apm.cmd ci
     at checkExecSyncError (child_process.js:616:11)
     at Object.execFileSync (child_process.js:634:15)
     at module.exports (D:\a\1\s\script\lib\run-apm-install.js:14:16)
     at Object.<anonymous> (D:\a\1\s\script\bootstrap:44:1)
     at Module._compile (internal/modules/cjs/loader.js:774:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
     at Module.load (internal/modules/cjs/loader.js:641:32)
     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
     at internal/main/run_main_module.js:17:11 {
   status: 1,
   signal: null,
   output: [ null, null, null ],
   pid: 6460,
   stdout: null,
```

**Comment by aminya** [comment]
I deprecated this fork in favour of the upstream for atom-community:
https://github.com/atom-community/atom/pull/76
